#!/usr/bin/env python3
"""Pack kernel.elf into the installer image (header + raw) and emit a C
translation unit that embeds it in the installer kernel."""
import struct, subprocess, sys

ELF, OUT_C = sys.argv[1], sys.argv[2]

TMPRAW = "/tmp/kresten-install-raw.bin"
subprocess.check_call(["objcopy", "-O", "binary", ELF, TMPRAW])
with open(TMPRAW, "rb") as f:
    raw = f.read()
entry = 0
hdr = subprocess.check_output(["readelf", "-h", ELF]).decode()
for line in hdr.splitlines():
    if "Entry point address" in line:
        entry = int(line.split()[-1], 16)
        break

img = b"KRSTENBR" + struct.pack("<II", 16 + len(raw), entry) + raw

lines = ["/* generated by pack_install_img.py - do not edit */",
         "#include <stdint.h>",
         "const unsigned char __install_img[] __attribute__((aligned(16))) = {"]
for i in range(0, len(img), 16):
    lines.append("    " + ", ".join("0x%02X" % b for b in img[i:i + 16]) + ",")
lines.append("};")
lines.append("const uint32_t __install_img_size = sizeof(__install_img);")
lines.append("")

with open(OUT_C, "w") as f:
    f.write("\n".join(lines) + "\n")

print("install image: %d bytes, entry 0x%X" % (len(img), entry))
